test commit
OlhaVarenyk/test_test pull request #1
Opened 2024-10-16 17:39 UTC by OlhaVarenyk

2024-10-16 20:42 UTC, hlazkov commented on playwright.config.js
> +    // baseURL: 'http://127.0.0.1:3000',
Its better to have baseUrl set here, not in tests or anywhere.

2024-10-16 20:47 UTC, hlazkov commented on tests/myTest.spec.js
> +  const productName = await page.textContent('[data-test="inventory-item-name"]');
This locator will resolve to all product names. I would suggest to pick first.
Also Its better to work with page with approach: `await page.locator(someLocator).textContent();` or `await page.getByTestId(someTestId).textContent();`. With such approach you will have page.locator.interaction, this code is better in sence of support and maintain.

2024-10-16 20:47 UTC, hlazkov commented on tests/myTest.spec.js
> +  expect(await page.textContent('[data-test="item-4-title-link"]')).toBe(productName);
Like for await in the correct place :)

2024-10-16 20:48 UTC, hlazkov commented on tests/myTest.spec.js
> +  await page.locator('[data-test="inventory-item"]').isHidden();
Should we have expect here instead of calling `.isHidden`?

2024-10-16 20:48 UTC, hlazkov requested changes
Just a few comments to fix. Good job here!

2024-10-17 15:59 UTC, AlinaZhykharieva approved these changes

2024-10-17 15:59 UTC, AlinaZhykharieva commented on tests/myTest.spec.js
> +  test("test1", async ({ page }) => {
names: test1 and test2 say nothing to us in the report. I would suggest to add more meaningful names for the scenarioas

2024-10-17 16:00 UTC, AlinaZhykharieva commented
Я б ще додала інформації до README, як запускати, що треба мати

2024-10-17 17:52 UTC, merged